name: Building Images

on:
  push:
    branches:
      - main

jobs:
  build-balance-alert:
    name: Build balance_alert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/Hcreak/general_web3_alert
          tags: |
            type=raw,value=balance-alert-{{branch}}-{{sha}}-{{date 'x'}}
            type=raw,value=balance-alert-latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./balance_alert/.
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-celestia-balance:
    name: Build celestia_balance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/Hcreak/general_web3_alert
          tags: |
            type=raw,value=celestia-balance-{{branch}}-{{sha}}-{{date 'x'}}
            type=raw,value=celestia-balance-latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./celestia_balance/.
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-tx-interval-alert:
    name: Build tx_interval_alert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/Hcreak/general_web3_alert
          tags: |
            type=raw,value=tx-interval-alert-{{branch}}-{{sha}}-{{date 'x'}}
            type=raw,value=tx-interval-alert-latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./tx_interval_alert/.
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-block-interval-alert:
    name: Build block_interval_alert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/Hcreak/general_web3_alert
          tags: |
            type=raw,value=block-interval-alert-{{branch}}-{{sha}}-{{date 'x'}}
            type=raw,value=block-interval-alert-latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./block_interval_alert/.
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-op-node-sync-alert:
    name: Build op_node_sync_alert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/Hcreak/general_web3_alert
          tags: |
            type=raw,value=op-node-sync-alert-{{branch}}-{{sha}}-{{date 'x'}}
            type=raw,value=op-node-sync-alert-latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./op_node_sync_alert/.
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}